title: Ben Johnson
description: Software engineering.
github_username:  bdjohnson529

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - docs
  - Gemfile
  - Gemfile.lock
  - package.json
  - static.json
  - node_modules


# Build settings
plugins:
  - jekyll-feed
  

sass:
  sass_dir: assets/css